services:
  - type: web
    name: bridgechat
    env: python
    plan: free  # Adjust based on your needs
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app
